
package Formularios;

import Clases.consultas;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ab_studio
 */
public class FormRegistro extends javax.swing.JFrame {

    int xMouse, yMouse;
    
    public FormRegistro() {
        initComponents();
        //Centra la ventanada al iniciar
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFormRegistro = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        favicon = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        emailIcon = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnVolver = new javax.swing.JPanel();
        btnVolverTxt = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JPanel();
        btnGuardarTxt = new javax.swing.JLabel();
        keyIcon = new javax.swing.JLabel();
        jtxtPass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        saveIcon = new javax.swing.JLabel();
        backIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jpFormRegistro.setBackground(new java.awt.Color(223, 224, 224));
        jpFormRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                    .addGap(0, 560, Short.MAX_VALUE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerLayout.createSequentialGroup()
                    .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jpFormRegistro.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        favicon.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        favicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoXS.png"))); // NOI18N
        favicon.setText("  Sietemesinos");
        jpFormRegistro.add(favicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 40));

        title.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        title.setText("Registrarse");
        jpFormRegistro.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userLabel.png"))); // NOI18N
        jpFormRegistro.add(userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jTextNombre.setBackground(new java.awt.Color(223, 224, 224));
        jTextNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextNombre.setForeground(new java.awt.Color(153, 153, 153));
        jTextNombre.setText(" Ingrese su nombre de usuario");
        jTextNombre.setToolTipText("");
        jTextNombre.setBorder(null);
        jTextNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextNombreMousePressed(evt);
            }
        });
        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });
        jpFormRegistro.add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 330, 30));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jpFormRegistro.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 330, 18));

        emailIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/correoIconS.png"))); // NOI18N
        jpFormRegistro.add(emailIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 30, -1));

        jtxtEmail.setBackground(new java.awt.Color(223, 224, 224));
        jtxtEmail.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtxtEmail.setForeground(new java.awt.Color(153, 153, 153));
        jtxtEmail.setText(" Ingrese su correo");
        jtxtEmail.setBorder(null);
        jtxtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtEmailMousePressed(evt);
            }
        });
        jtxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmailActionPerformed(evt);
            }
        });
        jpFormRegistro.add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 330, 30));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jpFormRegistro.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 330, 18));

        btnVolver.setBackground(new java.awt.Color(118, 183, 235));
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnVolverTxt.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnVolverTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolverTxt.setText("  VOLVER");
        btnVolverTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnVolverLayout = new javax.swing.GroupLayout(btnVolver);
        btnVolver.setLayout(btnVolverLayout);
        btnVolverLayout.setHorizontalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolverTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        btnVolverLayout.setVerticalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolverTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jpFormRegistro.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 80, 30));

        btnGuardar.setBackground(new java.awt.Color(118, 183, 235));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnGuardarTxt.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnGuardarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardarTxt.setText("GUARDAR");
        btnGuardarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGuardarLayout = new javax.swing.GroupLayout(btnGuardar);
        btnGuardar.setLayout(btnGuardarLayout);
        btnGuardarLayout.setHorizontalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardarTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        btnGuardarLayout.setVerticalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardarTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jpFormRegistro.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 90, 30));

        keyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/key.png"))); // NOI18N
        jpFormRegistro.add(keyIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        jtxtPass.setBackground(new java.awt.Color(223, 224, 224));
        jtxtPass.setForeground(new java.awt.Color(153, 153, 153));
        jtxtPass.setText(" ***********");
        jtxtPass.setBorder(null);
        jtxtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtPassMousePressed(evt);
            }
        });
        jpFormRegistro.add(jtxtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 330, 30));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jpFormRegistro.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 330, 18));

        saveIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/saveA.png"))); // NOI18N
        jpFormRegistro.add(saveIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 40, 30));

        backIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/previousM.png"))); // NOI18N
        jpFormRegistro.add(backIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFormRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFormRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void jTextNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextNombreMousePressed
        if (jTextNombre.getText().equals(" Ingrese su nombre de usuario")){
            jTextNombre.setText("");
            jTextNombre.setForeground(Color.black);
        }
        if (jtxtEmail.getText().isEmpty()){
            jtxtEmail.setText(" Ingrese su correo");
            jtxtEmail.setForeground(Color.gray);
        }
        if (String.valueOf(jtxtPass.getPassword()).isEmpty()){
            jtxtPass.setText(" ***********");
            jtxtPass.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jTextNombreMousePressed

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jtxtPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtPassMousePressed
        if (String.valueOf(jtxtPass.getPassword()).equals(" ***********")){
            jtxtPass.setText("");
            jtxtPass.setForeground(Color.black);
        }
        if (jTextNombre.getText().isEmpty()){
            jTextNombre.setText(" Ingrese su nombre de usuario");
            jTextNombre.setForeground(Color.gray);
        }
        if (jtxtEmail.getText().isEmpty()){
            jtxtEmail.setText(" Ingrese su correo");
            jtxtEmail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jtxtPassMousePressed

    private void btnVolverTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverTxtMouseClicked
        this.setVisible(false);
        FormLogin fr2 = new FormLogin();
        fr2.setVisible(true);
    }//GEN-LAST:event_btnVolverTxtMouseClicked

    private void btnGuardarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarTxtMouseClicked
        String nombreUsuario = jTextNombre.getText().trim();
        String claveUsuario = String.valueOf(jtxtPass.getPassword()).trim();
        String emailUsuario = jTextNombre.getText().trim();

        if (nombreUsuario.isEmpty()) {
            JOptionPane.showMessageDialog(this, " Ingresa un nombre de usuario válido.");
            return;
        }

        if (emailUsuario.isEmpty()) {
            JOptionPane.showMessageDialog(this, " Ingresa un correo válido.");
            return;
        }
        
        //if (claveUsuario.isEmpty() || claveUsuario.length() < 8) {
        if (claveUsuario.isEmpty()) {
            JOptionPane.showMessageDialog(this, " Ingresa una contraseña válida.");
            return;
        }
        

        //registrar el usuario
        consultas con = new consultas();
        boolean registroExitoso = con.guardarUsuario(nombreUsuario, emailUsuario, claveUsuario);

        if (registroExitoso) {
            //Registro exitoso
            JOptionPane.showMessageDialog(this, "Registro exitoso. Ahora puedes iniciar sesión.");
            this.setVisible(false);
            FormLogin login = new FormLogin();
            login.setVisible(true);
        } else {
            //Error en el registro (por ejemplo, usuario duplicado)
            JOptionPane.showMessageDialog(this, "Error al registrar el usuario. Intenta con un nombre diferente.");
        }
    }//GEN-LAST:event_btnGuardarTxtMouseClicked

    private void btnVolverTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverTxtMouseEntered
        btnVolver.setBackground(new Color(132, 200, 245));
    }//GEN-LAST:event_btnVolverTxtMouseEntered

    private void btnVolverTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverTxtMouseExited
        btnVolver.setBackground(new Color(118, 183, 235));
    }//GEN-LAST:event_btnVolverTxtMouseExited

    private void btnGuardarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarTxtMouseEntered
        btnGuardar.setBackground(new Color(132, 200, 245));
    }//GEN-LAST:event_btnGuardarTxtMouseEntered

    private void btnGuardarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarTxtMouseExited
        btnGuardar.setBackground(new Color(118, 183, 235));
    }//GEN-LAST:event_btnGuardarTxtMouseExited

    private void jtxtEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEmailMousePressed
        if (jtxtEmail.getText().equals(" Ingrese su correo")){
            jtxtEmail.setText("");
            jtxtEmail.setForeground(Color.black);
        }
        if (jTextNombre.getText().isEmpty()){
            jTextNombre.setText(" Ingrese su nombre de usuario");
            jTextNombre.setForeground(Color.gray);
        }
        if (String.valueOf(jtxtPass.getPassword()).isEmpty()){
            jtxtPass.setText(" ***********");
            jtxtPass.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jtxtEmailMousePressed

    private void jtxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backIcon;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JLabel btnGuardarTxt;
    private javax.swing.JPanel btnVolver;
    private javax.swing.JLabel btnVolverTxt;
    private javax.swing.JLabel emailIcon;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JLabel favicon;
    private javax.swing.JPanel header;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JPanel jpFormRegistro;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JPasswordField jtxtPass;
    private javax.swing.JLabel keyIcon;
    private javax.swing.JLabel saveIcon;
    private javax.swing.JLabel title;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
