/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Sesion;
import java.awt.BorderLayout;

/**
 *
 * @author luigi
 */
public class Homepage extends javax.swing.JFrame {
    private String username = Sesion.getUsername();
    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
        jLabelUsername.setText("Bienvenido " + username);
        
        //Centra la ventanada al iniciar
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFormRegistro = new javax.swing.JPanel();
        jLabelUsername = new javax.swing.JLabel();
        btnNuevaPartida = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnClasificaciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpFormRegistro.setBackground(new java.awt.Color(112, 145, 255));
        jpFormRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabelUsername.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabelUsername.setText("Inicio");

        btnNuevaPartida.setBackground(new java.awt.Color(204, 204, 204));
        btnNuevaPartida.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnNuevaPartida.setText("Nueva partida");
        btnNuevaPartida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaPartidaActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(204, 204, 204));
        btnVolver.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/previous.png"))); // NOI18N
        btnVolver.setText("Volver ");
        btnVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnClasificaciones.setBackground(new java.awt.Color(204, 204, 204));
        btnClasificaciones.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnClasificaciones.setText("Clasificaciones");
        btnClasificaciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClasificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClasificacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFormRegistroLayout = new javax.swing.GroupLayout(jpFormRegistro);
        jpFormRegistro.setLayout(jpFormRegistroLayout);
        jpFormRegistroLayout.setHorizontalGroup(
            jpFormRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFormRegistroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelUsername)
                .addGap(177, 177, 177))
            .addGroup(jpFormRegistroLayout.createSequentialGroup()
                .addGroup(jpFormRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClasificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpFormRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpFormRegistroLayout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpFormRegistroLayout.createSequentialGroup()
                            .addGap(113, 113, 113)
                            .addComponent(btnNuevaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jpFormRegistroLayout.setVerticalGroup(
            jpFormRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFormRegistroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelUsername)
                .addGap(38, 38, 38)
                .addComponent(btnNuevaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnClasificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFormRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpFormRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
        FormLogin fr2 = new FormLogin();
        fr2.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnNuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaPartidaActionPerformed
        abrirSeleccionJugador2();
    }//GEN-LAST:event_btnNuevaPartidaActionPerformed

    private void abrirSeleccionJugador2() {
        // Crear y mostrar el formulario de selección del jugador 2
        SeleccionJugador2 seleccion = new SeleccionJugador2();
        seleccion.setVisible(true);
        this.setVisible(false); // Opcional: ocultar la pantalla de inicio
    }
    
    private void btnClasificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClasificacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClasificacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClasificaciones;
    private javax.swing.JButton btnNuevaPartida;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jpFormRegistro;
    // End of variables declaration//GEN-END:variables
}
