/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.ConexionDB;
import Clases.Sesion;
import Clases.consultas;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author luigi
 */
public class SeleccionJugador2 extends javax.swing.JFrame {
    
    int xMouse, yMouse;

    /**
     * Creates new form SeleccionJugador2
     */
    public SeleccionJugador2() {
        initComponents();
        cargarUsuarios();
        //Centra la ventanada al iniciar
        this.setLocationRelativeTo(this);
    }
    
    private void cargarUsuarios() {
        //Obtener el nombre del usuario logueado
        String usuarioLogueado = Sesion.getUsername();

        //Crear una lista para los usuarios que se mostrarán en el JComboBox
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        cbUsers.setModel(model);
        
        //Agregar la opción por defecto al principio
        model.addElement("Seleccione contrincante...");
        cbUsers.setSelectedIndex(0); 

        try {
            
            ConexionDB db = new ConexionDB();
            Connection cn = db.conectar();
            // Conectar a la base de datos
            
            String query = "SELECT username FROM users WHERE username != ?";
            PreparedStatement pst = cn.prepareStatement(query);
            pst.setString(1, usuarioLogueado);
            
            //System.out.println("Ejecutando consulta: " + query);  // Depuración

            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                // Obtener el nombre de usuario de cada fila y agregarlo al JComboBox
                String username = rs.getString("username");
                model.addElement(username);
            }

            cn.close(); // Cerrar la conexión

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los usuarios: " + e.getMessage());
        }
        
        
         // Configurar el JComboBox para los colores
            DefaultComboBoxModel<String> modelColors = new DefaultComboBoxModel<>();
            cbColor.setModel(modelColors);

            // Agregar las opciones "Negras" y "Blancas"
            modelColors.addElement("Negras");
            modelColors.addElement("Blancas");

            // Establecer "Negras" como la opción seleccionada por defecto
            cbColor.setSelectedIndex(0);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFormRegistro = new javax.swing.JPanel();
        seleccionaJugTxt = new javax.swing.JLabel();
        cbUsers = new javax.swing.JComboBox<>();
        usuario2Txt = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        jtxtPass = new javax.swing.JPasswordField();
        keyIcon = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnVolver = new javax.swing.JPanel();
        btnVolverTxt = new javax.swing.JLabel();
        volverIcon = new javax.swing.JLabel();
        btnIniciarPart = new javax.swing.JPanel();
        IniciarPartTxt = new javax.swing.JLabel();
        entrarIcon = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        cbColor = new javax.swing.JComboBox<>();
        usuario2Txt1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jpFormRegistro.setBackground(new java.awt.Color(223, 224, 224));
        jpFormRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seleccionaJugTxt.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        seleccionaJugTxt.setText("Selecciona Jugador 2");
        jpFormRegistro.add(seleccionaJugTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        cbUsers.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        cbUsers.setBorder(null);
        cbUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUsersActionPerformed(evt);
            }
        });
        jpFormRegistro.add(cbUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 195, -1));

        usuario2Txt.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        usuario2Txt.setText("Color:");
        jpFormRegistro.add(usuario2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        lblPass.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblPass.setText("Contraseña:");
        jpFormRegistro.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        jtxtPass.setBackground(new java.awt.Color(223, 224, 224));
        jtxtPass.setForeground(new java.awt.Color(153, 153, 153));
        jtxtPass.setText(" ***********");
        jtxtPass.setBorder(null);
        jtxtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtPassMousePressed(evt);
            }
        });
        jpFormRegistro.add(jtxtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 200, 20));

        keyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/key.png"))); // NOI18N
        jpFormRegistro.add(keyIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jpFormRegistro.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 195, 20));

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnVolverTxt.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btnVolverTxt.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolverTxt.setText("  VOLVER");
        btnVolverTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnVolverLayout = new javax.swing.GroupLayout(btnVolver);
        btnVolver.setLayout(btnVolverLayout);
        btnVolverLayout.setHorizontalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVolverLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolverTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnVolverLayout.setVerticalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVolverTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpFormRegistro.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 130, 40));

        volverIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volverIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/previousM.png"))); // NOI18N
        jpFormRegistro.add(volverIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 40, 40));

        btnIniciarPart.setBackground(new java.awt.Color(0, 0, 0));
        btnIniciarPart.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarPart.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        IniciarPartTxt.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        IniciarPartTxt.setForeground(new java.awt.Color(255, 255, 255));
        IniciarPartTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IniciarPartTxt.setText("INICIAR PARTIDA");
        IniciarPartTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarPartTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IniciarPartTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IniciarPartTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnIniciarPartLayout = new javax.swing.GroupLayout(btnIniciarPart);
        btnIniciarPart.setLayout(btnIniciarPartLayout);
        btnIniciarPartLayout.setHorizontalGroup(
            btnIniciarPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnIniciarPartLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(IniciarPartTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnIniciarPartLayout.setVerticalGroup(
            btnIniciarPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnIniciarPartLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(IniciarPartTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpFormRegistro.add(btnIniciarPart, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, 40));

        entrarIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entrarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IniciarS.png"))); // NOI18N
        jpFormRegistro.add(entrarIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 40, 40));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                    .addGap(0, 440, Short.MAX_VALUE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerLayout.createSequentialGroup()
                    .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jpFormRegistro.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 30));

        cbColor.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        cbColor.setBorder(null);
        cbColor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbColorActionPerformed(evt);
            }
        });
        jpFormRegistro.add(cbColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 195, -1));

        usuario2Txt1.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        usuario2Txt1.setText("Usuario 2:");
        jpFormRegistro.add(usuario2Txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFormRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFormRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUsersActionPerformed

    private void btnVolverTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverTxtMouseClicked
        this.setVisible(false);
        Homepage hp2 = new Homepage();
        hp2.setVisible(true);
    }//GEN-LAST:event_btnVolverTxtMouseClicked

    private void btnVolverTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverTxtMouseEntered
        btnVolver.setBackground(new Color(0, 43, 85));
    }//GEN-LAST:event_btnVolverTxtMouseEntered

    private void btnVolverTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverTxtMouseExited
        btnVolver.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnVolverTxtMouseExited

    private void IniciarPartTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarPartTxtMouseClicked
        String user2 = (String) cbUsers.getSelectedItem();
        String password = new String(jtxtPass.getPassword()).trim();
        
        if(user2.equals("Seleccione contrincante...")){
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un contrincante.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if(password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa tu contraseña.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        consultas con = new consultas();
        boolean userEncontrado = con.consultarContrincante(user2, password);
        
        
        if(userEncontrado) {
            // Establecer conexión con la base de datos
            ConexionDB db = new ConexionDB();
            Connection cn = db.conectar();
            
            String player1 = Sesion.getUsername();
            String player2 = user2; 
            
            int player1Id = con.obtenerUsuarioId(player1, cn);
            int player2Id = con.obtenerUsuarioId(player2, cn);

            String colorPlayer2 = (String) cbColor.getSelectedItem();
            
            boolean partidaGuardada = con.guardarPartidaEnBD(player1Id, player2Id, colorPlayer2);

            if(partidaGuardada){
                this.setVisible(false);
                TableroAjedrez board = new TableroAjedrez(player1Id, player2Id, colorPlayer2);
                board.setVisible(true);
            } else{
                JOptionPane.showMessageDialog(this, "No se pudo iniciar la partida. Intente nuevamente.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_IniciarPartTxtMouseClicked

    private void IniciarPartTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarPartTxtMouseEntered
        btnIniciarPart.setBackground(new Color(0, 43, 85));
    }//GEN-LAST:event_IniciarPartTxtMouseEntered

    private void IniciarPartTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarPartTxtMouseExited
        btnIniciarPart.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_IniciarPartTxtMouseExited

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        this.setVisible(false);
        Homepage hp2 = new Homepage();
        hp2.setVisible(true);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void jtxtPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtPassMousePressed
        if (String.valueOf(jtxtPass.getPassword()).equals(" ***********")){
            jtxtPass.setText("");
            jtxtPass.setForeground(Color.black);
        }
    }//GEN-LAST:event_jtxtPassMousePressed

    private void cbColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbColorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionJugador2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionJugador2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionJugador2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionJugador2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionJugador2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IniciarPartTxt;
    private javax.swing.JPanel btnIniciarPart;
    private javax.swing.JPanel btnVolver;
    private javax.swing.JLabel btnVolverTxt;
    private javax.swing.JComboBox<String> cbColor;
    private javax.swing.JComboBox<String> cbUsers;
    private javax.swing.JLabel entrarIcon;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpFormRegistro;
    private javax.swing.JPasswordField jtxtPass;
    private javax.swing.JLabel keyIcon;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel seleccionaJugTxt;
    private javax.swing.JLabel usuario2Txt;
    private javax.swing.JLabel usuario2Txt1;
    private javax.swing.JLabel volverIcon;
    // End of variables declaration//GEN-END:variables
}
